DROP TABLE MEMBER purge;
CREATE TABLE MEMBER(
	MEMBER_ID VARCHAR2(20),
	MEMBER_PW VARCHAR2(15),
	MEMBER_NAME VARCHAR2(20),
	MEMBER_JUMIN1 NUMBER,
	MEMBER_JUMIN2 NUMBER,
	MEMBER_EMAIL VARCHAR2(25),
	MEMBER_EMAIL_GET VARCHAR2(7),
	MEMBER_MOBILE VARCHAR2(13),
	MEMBER_PHONE VARCHAR2(13),
	MEMBER_ZIPCODE VARCHAR2(13),
	MEMBER_ADDR1 VARCHAR2(70),
	MEMBER_ADDR2 VARCHAR2(70),
	MEMBER_ADMIN NUMBER,
	MEMBER_JOIN_DATE DATE
);

DROP TABLE ZIPCODE;
CREATE TABLE ZIPCODE (
  ID NUMBER,
  ZIPCODE VARCHAR2(7),
  SIDO VARCHAR2(10),
  GUGUN VARCHAR2(30),
  DONG VARCHAR2(36),
  RI VARCHAR2(60),
  BUNJI VARCHAR2(50),
  PRIMARY KEY (ID)
);

select * from MEMBER where MEMBER_ADMIN=0;

update MEMBER set MEMBER_ADMIN=1 where MEMBER_ADMIN=0 ;

select * from MEMBER;
select * from ZIPCODE;

DROP TABLE GOODS;
CREATE TABLE GOODS(
	GOODS_NUM NUMBER,
	GOODS_CATEGORY VARCHAR2(20),
	GOODS_NAME VARCHAR2(50),
	GOODS_CONTENT VARCHAR2(3000),
	GOODS_SIZE VARCHAR2(10),
	GOODS_COLOR VARCHAR2(20),
	GOODS_AMOUNT NUMBER,
	GOODS_PRICE NUMBER,
	GOODS_IMAGE VARCHAR2(50),
	GOODS_BEST NUMBER,
	GOODS_DATE DATE,
	PRIMARY KEY(GOODS_NUM)
);
CREATE TABLE BASKET(
	BASKET_NUM NUMBER,
	BASKET_MEMBER_ID VARCHAR2(20),
	BASKET_GOODS_NUM NUMBER,
	BASKET_GOODS_AMOUNT NUMBER,
	BASKET_GOODS_SIZE VARCHAR2(20),
	BASKET_GOODS_COLOR VARCHAR2(20),
	BASKET_DATE DATE,
	PRIMARY KEY(BASKET_NUM)
);

CREATE TABLE GOODS_ORDER(
	ORDER_NUM NUMBER,
	ORDER_TRADE_NUM VARCHAR2(50),
	ORDER_TRANS_NUM VARCHAR2(50),
	ORDER_GOODS_NUM	NUMBER,
	ORDER_GOODS_NAME VARCHAR2(50),
	ORDER_GOODS_AMOUNT NUMBER,
	ORDER_GOODS_SIZE VARCHAR2(20),
	ORDER_GOODS_COLOR VARCHAR2(20),
	ORDER_MEMBER_ID VARCHAR2(20),
	ORDER_RECEIVE_NAME VARCHAR2(20),
	ORDER_RECEIVE_ADDR1 VARCHAR2(70),
	ORDER_RECEIVE_ADDR2 VARCHAR2(70),
	ORDER_RECEIVE_PHONE VARCHAR2(13),
	ORDER_RECEIVE_MOBILE VARCHAR2(13),
	ORDER_MEMO VARCHAR2(3000),
	ORDER_SUM_MONEY NUMBER,
	ORDER_TRADE_TYPE VARCHAR2(20),
	ORDER_TRADE_DATE DATE,
	ORDER_TRADE_PAYER VARCHAR2(20),
	ORDER_DATE DATE,
	ORDER_STATUS NUMBER,
	PRIMARY KEY(ORDER_NUM)
);
DELETE basket;
COMMIT

SELECT * FROM basket;

DROP TABLE MVCBOARD purge;

CREATE TABLE MVCBOARD(
	boardNum			varchar2(20)	primary key,
	boardName			varchar2(20),
	boardPass			varchar2(20),
	boardSubject		varchar2(20),
	boardContent		varchar2(20),
	boardFile			varchar2(20),
	boardReplyRef 	varchar2(20),
	boardReplyLev 	varchar2(20),
	boardReplySeq 	varchar2(20),
	boardReadcount	varchar2(20),
	boardDate 			date
);

select * from MVCBOARD;

delete from MVCBOARD;
