/* 회원 정보 관련 부분 특별히 추가할 부분이 없으므로 기존 테이블을 그대로 사용*/
DROP TABLE MEMBER purge;
CREATE TABLE MEMBER(
	MEMBER_ID VARCHAR2(20),
	MEMBER_PW VARCHAR2(15),
	MEMBER_NAME VARCHAR2(20),
	MEMBER_JUMIN1 NUMBER,
	MEMBER_JUMIN2 NUMBER,
	MEMBER_EMAIL VARCHAR2(25),
	MEMBER_EMAIL_GET VARCHAR2(7),
	MEMBER_MOBILE VARCHAR2(13),
	MEMBER_PHONE VARCHAR2(13),
	MEMBER_ZIPCODE VARCHAR2(13),
	MEMBER_ADDR1 VARCHAR2(70),
	MEMBER_ADDR2 VARCHAR2(70),
	MEMBER_ADMIN NUMBER,
	MEMBER_JOIN_DATE DATE
);
DROP TABLE ZIPCODE;
CREATE TABLE ZIPCODE (
  ID NUMBER,
  ZIPCODE VARCHAR2(7),
  SIDO VARCHAR2(10),
  GUGUN VARCHAR2(30),
  DONG VARCHAR2(36),
  RI VARCHAR2(60),
  BUNJI VARCHAR2(50),
  PRIMARY KEY (ID)
);

update MEMBER set MEMBER_ADMIN=1 where MEMBER_ID='kkh3260';

select * from MEMBER;
select * from ZIPCODE;

/* 상품 관련 부분 */ 
DROP TABLE GOODS purge;
CREATE TABLE GOODS(
	GOODS_NUM NUMBER,
	GOODS_CATEGORY 	VARCHAR2(30),
	GOODS_NAME 		VARCHAR2(100),
	GOODS_CONTENT 	VARCHAR2(3000),
	GOODS_SIZE VARCHAR2(10),
	/* color제거 country, type,variety,ABV(도수?)추가*/
	GOODS_COUNTRY 	VARCHAR2(30),
	GOODS_ABV 			VARCHAR2(30),
	GOODS_AMOUNT 	NUMBER,
	GOODS_PRICE 		NUMBER,
	GOODS_IMAGE 		VARCHAR2(2000),
	/* 인기상품 여부 */
	GOODS_BEST 						NUMBER,
	/* 상품 조회수*/
	GOODS_READCOUNT 			NUMBER,
	/* 상품 구매수 */
	GODDS_BUYCOUNT				NUMBER,	
	GOODS_DATE 			DATE,
	PRIMARY KEY(GOODS_NUM)
);

select * from goods;
/*장바구니*/
DROP TABLE BASKET purge;
CREATE TABLE BASKET(
	BASKET_NUM NUMBER,
	BASKET_MEMBER_ID VARCHAR2(20),
	BASKET_GOODS_NUM NUMBER,
	BASKET_GOODS_AMOUNT NUMBER,
	BASKET_DATE DATE,
	PRIMARY KEY(BASKET_NUM)
);

select * from BASKET;

/*상품 주문서 ? 수정중 */
DROP TABLE GOODS_ORDER purge;
CREATE TABLE GOODS_ORDER(
	ORDER_NUM NUMBER,
	ORDER_TRADE_NUM VARCHAR2(50),
	ORDER_TRANS_NUM VARCHAR2(50),
	ORDER_GOODS_NUM	NUMBER,
	ORDER_GOODS_NAME VARCHAR2(100),
	ORDER_GOODS_AMOUNT NUMBER,
	ORDER_MEMBER_ID VARCHAR2(20),
	ORDER_RECEIVE_NAME VARCHAR2(20),
	ORDER_RECEIVE_ADDR1 VARCHAR2(70),
	ORDER_RECEIVE_ADDR2 VARCHAR2(70),
	ORDER_RECEIVE_PHONE VARCHAR2(13),
	ORDER_RECEIVE_MOBILE VARCHAR2(13),
	ORDER_MEMO VARCHAR2(3000),
	ORDER_SUM_MONEY NUMBER,
	ORDER_TRADE_TYPE VARCHAR2(20),
	ORDER_TRADE_DATE DATE,
	ORDER_TRADE_PAYER VARCHAR2(20),
	ORDER_DATE DATE,
	ORDER_STATUS NUMBER,
	PRIMARY KEY(ORDER_NUM)
);
DELETE basket;
COMMIT

SELECT * FROM GOODS_ORDER;

select * from goods order by goods_num;

SELECT * FROM basket;

DROP TABLE MVCBOARD purge;

CREATE TABLE MVCBOARD(
	BOARDNUMBER			VARCHAR2(20)	primary key,
	/* 게시판 카테고리 추가 */
	BOARD_CATEGORY		VARCHAR2(20),
	/* 게시판은 로그인 해서 사용할 것이기 때문의 기존의 
	 * bordname과 bordpass를 삭제함 
	 * MEMBER_ID를 통해서 작성자 확인을 하면됨*/
	MEMBER_ID 				VARCHAR2(20),
	boardSubject				VARCHAR2(20),
	boardContent				VARCHAR2(20),
	boardFile					VARCHAR2(20),
	boardReplyRef 			VARCHAR2(20),
	boardReplyLev 			VARCHAR2(20),
	boardReplySeq 			VARCHAR2(20),
	boardReadcount			VARCHAR2(20),
	boardDate 			date
);

select * from MVCBOARD;

delete from MVCBOARD;
